src/foundation/materials/singles/MToonSingleMaterialNode.ts

The iOS14 updates gl.MAX_COMBINED_TEXTURE_IMAGE_UNITS. We can use 16 number of texture in a shader.
I updated the MToon material to support the increasing the number of usable textures.

support iOS14 for MToon material

---

src/foundation/components/SceneGraphComponent.ts
src/foundation/geometry/Primitive.ts
src/foundation/math/AABB.ts
src/foundation/memory/Accessor.ts
src/foundation/memory/AccessorBase.ts
src/foundation/memory/BufferView.ts
src/foundation/memory/FlexibleAccessor.ts

This PR fixes #637.
I fixed the following:
1. In the constructor of accessorClasses does not take a min and a max property.
2. When the accessor is interleaved(multiple accessor share single bufferView), the byte length of the dataView in an accessor is strange.
3. When the accessor is interleaved, element count in an accessor is strange.

Fix min and max calculation in accessor interleaved model

---

src/foundation/cameras/AbstractCameraController.ts
src/foundation/cameras/OrbitCameraController.ts
src/foundation/cameras/WalkThroughCameraController.ts

If a user attaches the camera controller component to an entity that has the camera component, the original z near and z far are ignored and the camera component adopts the calculated value by the camera controller. The calculation method of them is different between the orbit type and the walkthrough type.
Here, there are problems.
1. When a user attaches the camera controller component, the user cannot control z near and z far manually.
2. If a user changes the camera controller type, some objects appear/disappear on the display because z near and far are different between camera controller types.
To improve them, I created an abstract class of camera controller classes. The abstract class has the following:
1. The flag of the auto calculation of z near and z far
2. A calculation method …

Unify the calculation method of zNear and zFar

---

src/webgl/WebGLStrategyCommonMethod.ts
src/webgl/WebGLStrategyFastestWebGL1.ts
src/webgl/WebGLStrategyUniform.ts

This PR fixes #667. I fixed the following problem.
[problem]
In the $render method, a model should be drawn in the following order:
(opaque primitives) -> (transparent primitives)
However, a model was drawn in the following order:
(opaque meshes and opaque and transparent meshes) -> (transparent meshes and opaque and transparent meshes)
That means if a mesh has both types of transparent and opaque primitive, the $render($common_render) method drew the mesh twice.

Avoid duplicate drawing

---

samples/test_e2e/GltfImporter-skinning-mat44/main.js
samples/test_e2e/GltfImporter-skinning-vec4-1/main.js
samples/test_e2e/GltfImporter-skinning-vec4-2/main.js
src/foundation/misc/RnPromise.test.ts

This PR fixes #669.
There are two errors. One is in the unit-test for the RnPromise. Another one is in the e2e-tests of the skinning.
A unit test for the RnPromise is failed because, 'resolve' variable in the following link is an object of the RnPromise, however the 'resolve' is used as function in the next line.
https://github.com/actnwit/RhodoniteTS/blob/38144eb92ddc7cd5b67614d14e99d08dcfb8d651/src/foundation/misc/RnPromise.test.ts#L80
I changed the usage of the 'resolve'.
The e2e-tests of skinning is failure because, there are the default setting of the rhodonite uses too many uniforms. The mac mini supports 1024 uniforms of vector in the vertex shader. However, the Rhodonite uses more than 1024 vectors by skinning. I decrease the number of uniforms by set parameter to …

Support tests on mac mini

---

src/commontypes/glTF.ts
src/foundation/importer/ModelConverter.ts

It was found that when loading glTF, if there are multiple materials with the same material index and different attributes (skinning and morphing), the reuse of the materials does not occur as expected. To improve this, i attempted to change the keys indexed to reuse the material to include not only the material index but also other attributes.
This problem occurs because Rhodonite Materials with different attribute values are repeatedly assigned to the rnMaterials using the same material index as the key.
https://github.com/actnwit/RhodoniteTS/blob/8d7a9aa90df7a78e8f0c1934194699581565509c/src/foundation/importer/ModelConverter.ts#L785
(call the Rn.Material.getAllMaterials() method before and after the change in Rhodonite and check the behavior by comparing the number of its elements. The …

Reuse materials, if those are duplicated

---

src/foundation/geometry/Mesh.ts
src/foundation/helpers/MaterialHelper.ts
src/foundation/importer/GltfImporter.ts
src/foundation/importer/ModelConverter.ts
src/foundation/materials/core/Material.ts
src/foundation/materials/singles/MToonSingleMaterialNode.ts
src/foundation/materials/singles/PbrShadingSingleMaterialNode.ts
src/webgl/shaderity_shaders/PbrSingleShader/PbrSingleShader.frag
src/webgl/shaderity_shaders/PbrSingleShader/PbrSingleShader.vert
src/webgl/shaderity_shaders/common/perturbedNormal.glsl
src/webgl/shaders/GLSLShader.ts
src/webgl/shaders/MToonShader.ts

This PR improves the speed of loading when the gltf2.0 model does not have a tangent attribute. Furthermore, this PR fixes #612 in a normal 1.0 case.
I implemented a tangent calculation in a shader with reference to http://www.thetenthplanet.de/archives/1180. This implementation computes the tangent in the shader in real-time. We do not need to precompute the tangent anymore, thus reducing the load time.
For this implementation, I changed the tangent calculation mode as follows
0: Do not correct for normal using a normal map (do not set the normal map).
1: If there is a tangent in the gltf, use its value, otherwise the shader will calculate it (default).
2: If there is a tangent in the gltf, use its value, otherwise, pre-calculate it in javascript (typescript) as before.
3: Ignore the …

Tangent calculation in shader

---

src/foundation/importer/ModelConverter.ts
src/foundation/materials/singles/PbrShadingSingleMaterialNode.ts
src/webgl/shaderity_shaders/PbrSingleShader/PbrSingleShader.frag

This PR supports normalTextureInfo.scale and occlusionTextureInfo.strength property in GTF2.0.
Supporting normalTextureInfo.scale fixes #612.

Support normal scale and occlusion strength

---

src/foundation/core/Config.ts
src/foundation/materials/core/AbstractMaterialNode.ts
src/foundation/materials/core/Material.ts
src/foundation/materials/core/ShaderityUtility.ts
src/foundation/memory/Buffer.ts
src/foundation/misc/MiscUtil.ts
src/webgl/WebGLContextWrapper.ts
src/webgl/WebGLResourceRepository.ts
src/webgl/WebGLStrategyFastest.ts
src/webgl/WebGLStrategyUniform.ts
src/webgl/getRenderingStrategy.ts
src/webgl/shaderity_shaders/common/prerequisites.glsl
src/webgl/shaders/GLSLShader.ts

This PR's key points are:
- Support the property access to huge logical shader memory using UBO & DataTexture access in Rn.ProcessApproach.FastestWebGL2.
- The first part of Memory data in BufferUse.GPUInstanceData are stored the range of data that fits in the UBO, and store the rest in data textures.
- Each shader property getters don't need to worry about the boundaries of UBO and data texture.
- Others, such as refactoring
- It takes so long time to compile shaders in Rn.ProcessApproach.FastestWebGL2 mode currently. This may be due to the way the UBO blocks are defined in large numbers.

Support generic purpose UBO access

---

src/webgl/shaders/GLSLShader.ts

The 'texture2D' function does not work on webGL2.0. I fixed it.

Fix texture fetch functions

---

src/commontypes/CommonTypes.ts
src/foundation/core/Component.ts
src/foundation/core/Config.ts
src/foundation/core/GlobalDataRepository.ts
src/foundation/core/MemoryManager.ts
src/foundation/definitions/CompositionType.ts
src/foundation/definitions/ShaderSemantics.ts
src/foundation/geometry/Plane.ts
src/foundation/geometry/Primitive.ts
src/foundation/geometry/Sphere.ts
src/foundation/importer/ModelConverter.ts
src/foundation/materials/core/Material.ts
src/foundation/memory/Accessor.test.ts
src/foundation/memory/AccessorBase.ts
src/foundation/memory/Buffer.test.ts
src/foundation/memory/Buffer.ts
src/foundation/memory/BufferView.test.ts
src/foundation/memory/BufferView.ts
src/webgl/WebGLStrategyFastest.ts
src/webgl/WebGLStrategyUniform.ts
src/webgl/shaderity_shaders/common/prerequisites.glsl
src/webgl/shaders/GLSLShader.ts

This PR includes the following points:
- Add shader parameter getter like `fetchVec3No16BytesAligned`, which is not 16bytes aligned for byte offset calculation.
- Support CompositionType.*Array like CompositionType.Mat3Array truely.
- Remove vec3 -> vec4 data copy of VRM/glTF morph targets data because of supporting `fetch*No16BytesAligned` at this time, which is not 16bytes aligned for byte offset calculation.

Add shader parameter getter like `fetchVec3No16BytesAligned`, which is not 16bytes aligned for byte offset calculation.

---

src/foundation/definitions/CompositionType.ts
src/foundation/definitions/ProcessApproach.ts
src/foundation/materials/core/AbstractMaterialNode.ts
src/foundation/materials/core/Material.ts
src/foundation/misc/MiscUtil.ts
src/foundation/textures/Texture.ts
src/webgl/WebGLContextWrapper.ts
src/webgl/WebGLResourceRepository.ts
src/webgl/WebGLStrategyFastest.ts
src/webgl/WebGLStrategyUniform.ts
src/webgl/getRenderingStrategy.ts
src/webgl/shaders/GLSLShader.ts

This PR includes the following loading speed optimizations.
- Add the faster concatArrayBuffer function named `concatArrayBuffer2`
- Skip the `gl.getUniformLocation()` if the `isUniformExist` is false.
- where `isUniformExist` is `CompositionType.isTexture(info.compositionType) || info.needUniformInFastest || ProcessApproach.isUniformApproach(System.getInstance().processApproach);`
This PR also includes the following fixes.
- Fix to work properly with isDebugMode == false
- Add the `this.__width = 1;` and `this.__height = 1;` to Texture::generate1x1TextureFrom function
Rhodonite works faster if you pass `false` to the  `isDebug` argument of System::setProcessApproachAndCanvas method like this.
```javascript
const isDebug = false;
const gl = system.setProcessApproachAndCanvas(strategy, …
```

Loading speed optimizations

---

src/foundation/importer/ModelConverter.ts

Fixes: https://github.com/actnwit/RhodoniteTS/issues/701
Fixed a problem where OrthographicCamera defined in glTFs could not be loaded correctly.
An undefined value was being assigned to xmag, so it has been changed so that it is assigned correctly.
Tried tendering [Camera.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cameras/glTF)

Fix initialization of othographic camera

---

samples/test_e2e/ShadowMap/main.ts
samples/test_e2e/ShadowMapDebugMode/main.ts
src/foundation/materials/singles/ShadowMapDecodeClassicSingleMaterialNode.ts
src/webgl/shaderity_shaders/ShadowMapDecodeClassicSingleShader/ShadowMapDecodeClassicSingleShader.frag
src/webgl/shaders/ShadowMapDecodeClassicShader.ts

- Change the specification of shadow mapping (see below)
I changed the colour specification of the shadow area like following:
before: (shadow colour) = (diffuse colour) * (shadow coefficient)
after:  (shadow colour) = (shadow colour)

improvement: simplify the shader semantics parameter in ShadowMapDecodeClassicSingleMaterialNode

---

src/foundation/materials/singles/DepthEncodeSingleMaterialNode.ts

If there are two or more DephEncodeSingleMaterialNodes and the parameters(zNear and zFar) of the cameras that capture them are the same, the uniform value will not be updated. I fixed it.

fix: update uniform value correctly in the DepthEncodeSingleMaterialNode

---

.eslintrc.json

The value of the eqeqeq rule in eslintrc.json was wrong. I corrected it.
Here is the reference.
https://eslint.org/docs/2.0.0/rules/eqeqeq

fix: eslint settings

---

src/foundation/importer/AnimationAssigner.ts
src/foundation/importer/DrcPointCloudImporter.ts
src/foundation/importer/Gltf1Importer.ts
src/foundation/importer/Gltf2Importer.ts
src/foundation/importer/GltfImporter.ts

If data of image property of gltf2 is specified by buffer view like the following attached image, the rhodonite cannot load the image data. I fixed it.

fix: support the image data stored in the bufferView of gltf2.0

---

src/foundation/importer/Gltf2Importer.ts

The Rhodonite is failing to load ktx2 texture when the ktx2 is embedded in the Uri of gltf.images as data URI.

fix: enable to read data URI in ktx2 file

---

src/foundation/helpers/RenderableHelper.ts
src/foundation/textures/RenderBuffer.ts
src/webgl/WebGLResourceRepository.ts

Currently, the number of sampling for the MSAA depth value is fixed at 4. In this PR, the number of sampling is selectable.

feat: enable to configure the sample count for MSAA

---

src/foundation/textures/CubeTexture.ts

This PR prevents unwanted loading of the MeshRendererComponent.$load method.
The MeshRendererComponent.$load method tries to load the texture from URI if CubeTexture.__startedToLoad is false, which is not necessary when creating a cube map with a typed array, so we changed CubeTexture.__startedToLoad to true.

fix: avoid needless cube map loading in MeshRendererComponent.$load

---

samples/simple/VideoTexture/index.html
samples/simple/VideoTexture/main.ts
samples/test_e2e/GltfImporter-draco-extension/index.html
samples/test_e2e/GltfImporter-draco-extension/main.ts
samples/test_e2e/GltfImporter-ibl-1/index.html
samples/test_e2e/GltfImporter-ibl-1/main.ts
src/foundation/exporter/Gltf2Exporter.ts
src/foundation/textures/AbstractTexture.ts

Add a check to "this.__htmlImageElement" since it was undefined.
This.__htmlImageElement!.width is undefined, so change it to use a pre-set value.
As far as I understand, this is my response to avoid errors.
Please review it.
Please let me know if further modifications are needed.
┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=762801649)

fix: glTFExporter　error

---

src/foundation/materials/core/ShaderityUtility.ts

The getShaderDataRefection method in shaderity utility is too long. I separate the method into small parts.
Furthermore, I removed an 'any type' object.

refactor: separate getShaderDataRefection method in shaderity utility

---

src/foundation/core/GlobalDataRepository.ts
src/foundation/helpers/MaterialHelper.ts
src/foundation/materials/core/Material.ts
src/foundation/materials/singles/ShaderitySingleMaterialNode.ts

This PR supports a material that is created by Shaderity.ShaderityObjectCreator.
Currently, this material node can be used when the webgl strategy is 'uniform' only

feat: shaderity material node

---

src/foundation/components/SceneGraphComponent.ts

fix: error behavior when is*gizmo.isVisible = false

fix: is visible gizmo

---

src/index.ts

This PR exports the type of MutableScalar outside the library.

chore: export type

---

src/foundation/core/Config.ts

We cannot change maxSkeletalBoneNumberForUniformMode option now.
However, we need to change this option when the model that we want to display has more than 50 skeletal bones.
So I export this option

feat: export max skeletal bone number for uniform mode option

---

src/webgl/shaderity_shaders/MToon0xSingleShader/MToon0xSingleShader.frag.glsl
src/webgpu/shaderity_shaders/MToon0xSingleShader/MToon0xSingleShader.frag.wgsl

- Simplified shade color and lit color calculations by integrating the srgbToLinear conversion directly into the texture sampling process.
- Removed redundant srgbToLinear calls for outline color, improving clarity in the shader code.
- Enhanced readability and maintainability of the shader code by streamlining color processing logic.

refactor: optimize color calculations in MToon0xSingleShader

---

src/webgpu/WebGpuResourceRepository.ts

- Added null check for texture before attempting to destroy and delete it, preventing potential runtime errors.
- Enhanced mipmap generation logic by ensuring proper cleanup of associated texture views and bind groups before destroying the texture.
- Streamlined resource management to improve performance and reliability during texture operations.

fix: improve texture management in WebGpuResourceRepository

---

src/foundation/gizmos/AABBGizmo.ts

- Added a call to `_update()` in the `AABBGizmo` class after setting the mesh component, ensuring that the gizmo is correctly initialized and updated with the latest mesh data.

feat: update AABBGizmo to ensure proper initialization

---

src/foundation/renderer/Expression.ts
src/foundation/renderer/RenderPass.ts

- Added a call to `tryToSetUniqueName` in the `clone` method of both `Expression` and `RenderPass` classes to ensure that cloned instances have unique names, improving object management and preventing naming conflicts.

fix: set unique name when cloning in Expression and RenderPass classes

---

src/foundation/geometry/Mesh.ts
src/foundation/renderer/RenderPass.ts
src/foundation/renderer/pipelines/ForwardRenderPipeline.ts
src/webgl/WebGLStrategyDataTexture.ts
src/webgl/WebGLStrategyUniform.ts
src/webgpu/WebGpuStrategyBasic.ts

- Updated the Mesh class to categorize primitives into opaque, translucent, blend with ZWrite, and blend without ZWrite, improving rendering logic.
- Modified RenderPass to manage rendering flags for translucent and blend primitives, replacing the previous transparent primitive handling.
- Adjusted ForwardRenderPipeline to set appropriate rendering flags for different primitive types, ensuring correct rendering behavior.
- Updated WebGL and WebGPU strategies to reflect changes in primitive rendering logic, enhancing overall rendering performance and flexibility.

feat: enhance mesh and render pass handling for primitive types

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

Since the initial release, new versions made substantial changes to dev containers. This commit upgrades the versions to the latest LTS, updates JSON according to the latest scheme, and fixes comment lines with active links.

fix: update devcontainer for 2025h1

---

.github/workflows/lint-pr.yml

This pull request updates the version of the `action-semantic-pull-request` GitHub Action in the `.github/workflows/lint-pr.yml` file to benefit from more recent node in new version and fixes.

fix: update lint action for more recent version
