src/foundation/materials/core/Material.ts
src/webgl/WebGLStrategyCommonMethod.ts

To optimize, I reduced if statements of blend settings.

Reduce if statements

---

src/foundation/geometry/Mesh.ts
src/foundation/geometry/Primitive.ts

Instance mesh objects share primitives with original Mesh

---

src/foundation/cameras/AbstractCameraController.ts
src/foundation/cameras/OrbitCameraController.ts
src/foundation/cameras/WalkThroughCameraController.ts

This PR fixes #612 in normal 1.0 case.

Tangent calculation in shader

---

src/foundation/components/CameraComponent.ts

**[breaking change] setter and getter of cornerInner**
I fixed the spelling mistake of the cornerInner.

Fix spelling mistake

---

src/foundation/materials/singles/DepthEncodeSingleMaterialNode.ts
src/foundation/materials/singles/EnvConstantSingleMaterialNode.ts

This PR solves build error in the CI

Correcting path error

---

src/foundation/system/System.ts

This PR helps users to choose Rn.ProcessApproach without errors on mobile devices.

feat: display an alert for mobile devices to avoid too many uniform error

---

src/foundation/components/MeshComponent.ts
src/foundation/components/SceneGraphComponent.ts
src/foundation/geometry/Mesh.ts
src/foundation/geometry/Primitive.ts
src/foundation/math/AABB.ts
src/foundation/memory/AccessorBase.ts

The purpose of this PR is the following:
1. feat
- support recalculation of world AABB in the system.process method when the position attribute is updated
2. fix
- accessor.copyFromTypedArray method can take a typed array of scalar as an argument
3. refactor
- avoid creating useless objects such as a vector and an AABB.

feat: update world AABB in scene graph component when the position attribute is updated 

---

src/foundation/components/MeshComponent.ts
src/foundation/geometry/Mesh.ts
src/foundation/geometry/Primitive.ts
src/webgl/WebGLResourceRepository.ts
src/webgl/WebGLStrategyCommonMethod.ts
src/webgl/WebGLStrategyFastest.ts
src/webgl/WebGLStrategyUniform.ts

feat
- update VBO and VAO when the position attribute is updated
fix
- delete vertexHandles in primitive.delete3DAPIVertexData to detect that 3DAPIVertexData has been removed
**Breaking Change**
- remove resendVertexBuffer and createVertexDataResources in WebGLResourceRepository.ts

update VBO and VAO when the position attribute is updated

---

src/foundation/importer/DrcPointCloudImporter.ts

- Remove options argument in DrcPointCloudImporter.importPointCloudToPrimitive (this is because the options are not used)
- Attach type to return value of importer methods in DrcPointCloudImporter

Improvement: DrcPointCloudImporter.importPointCloudToPrimitive

---

src/webgl/WebGLResourceRepository.ts

This PR will fix the error in CI.

fix: correct type of WebGLObject

---

README.md

doc:  update how to try samples in README

---

src/foundation/cameras/OrbitCameraController.ts

feat: fix the center of the orbit camera controller to the AABB centre of the target

---

src/foundation/math/Quaternion.ts

fix: spherical linear interpolation

---

src/foundation/textures/CubeTexture.ts
src/webgl/WebGLResourceRepository.ts

This PR allows you to import typedArray background cube maps etc.

feat: support for importing typedArray cubemaps

---

src/foundation/importer/ModelConverter.ts

fix: apply autoDetectTextureTransparency to base and diffuse texture only

---

samples/test_e2e/Gltf1Importer/test.js
samples/test_e2e/Gltf2Importer-GlareEffect/test.js
samples/test_e2e/Gltf2Importer/test.js
samples/test_e2e/GltfImporter-alpha-blend-mode/test.js
samples/test_e2e/GltfImporter-animation-in-second-bin-file/test.js
samples/test_e2e/GltfImporter-draco-extension/test.js
samples/test_e2e/GltfImporter-iOS/test.js
samples/test_e2e/GltfImporter-ibl-0/test.js
samples/test_e2e/GltfImporter-ibl-1-webgl2/test.js
samples/test_e2e/GltfImporter-ibl-1/test.js
samples/test_e2e/GltfImporter-interpolation/test.js
samples/test_e2e/GltfImporter-multiUV/test.js
samples/test_e2e/GltfImporter-orbit-moving/test.js
samples/test_e2e/GltfImporter-skinning-mat44/test.js
samples/test_e2e/GltfImporter-skinning-vec4-1/test.js
samples/test_e2e/GltfImporter-skinning-vec4-2/test.js
samples/test_e2e/GltfImporter-sparse-accessor/test.js
samples/test_e2e/GltfImporter-specify-noLight/test.js
samples/test_e2e/GltfImporter-texture-settings/test.js
samples/test_e2e/GltfImporter-texture-transform/test.js
samples/test_e2e/GltfImporter-walk-through-eye-direction-moving/test.js
samples/test_e2e/GltfImporter-walk-through-fixed-direction-moving/test.js
samples/test_e2e/GltfImporter/test.js
samples/test_e2e/MultiPass/test.js
samples/test_e2e/VRMAnimation/test.js
samples/test_e2e/VRMImporter/test.js

Add the following timeout setting row to some remained test files.
```
await page.setDefaultNavigationTimeout(180000);
```

test: Add timeout for testing

---

src/foundation/importer/ModelConverter.ts

the "uint8Array.buffer.slice(byteOffset + uint8Array.byteOffset)," is not necessary

fix: switch to this.__rewrapWithTypedArray

---

src/foundation/exporter/Gltf2Exporter.ts

gltf json formatting
JSON.stringify add argument
┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=765597130)

feat: gltf json formatting

---

src/foundation/components/AnimationComponent.ts
src/foundation/core/EntityRepository.ts
src/foundation/misc/MiscUtil.ts
src/xr/WebXRInput.ts

This is all refactoring PRs
- refactor: change defaultValueWithCallback to valueWithCompensation
- refactor: change defaultValue to valueWithDefault

refactor: miscutil

---

src/foundation/math/MutableVector3.ts
src/foundation/math/MutableVector4.ts

fix: fromCopyArray*

---

src/foundation/misc/MiscUtil.ts
src/webgl/WebGLResourceRepository.ts

fix: disable UBO for safari

---

src/foundation/definitions/ShaderSemantics.ts
src/types/glTF.ts
src/types/glTF1.ts
src/types/glTF2.ts

for more restriction as TypeScript Type

fix: switch type anotation "Object" to "object"

---

src/types/WebGLConstants.ts

This is from https://gist.github.com/TimvanScherpenzeel/1f4218a563789db17955a1926c8a8ee0 . 
Thank you TimvanScherpenzeel-san and all contributors of it!

feat: add WebGLConstants.ts

---

src/foundation/importer/DrcPointCloudImporter.ts
src/foundation/importer/Gltf2Importer.ts
src/foundation/misc/RnPromise.test.ts
src/foundation/misc/RnPromise.ts
src/types/RnM2.ts
src/types/glTF2.ts

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=762760936)

refactor: RnPromise

---

src/foundation/exporter/Gltf2Exporter.ts

Fix the exporter codes to pass the glTF2 validator.

fix: gltf2 exporter

---

.vscode/settings.json
src/effekseer/EffekseerComponent.ts
src/foundation/cameras/OrbitCameraController.ts
src/foundation/cameras/WalkThroughCameraController.ts
src/foundation/components/Animation/AnimationComponent.ts
src/foundation/components/BlendShape/BlendShapeComponent.ts
src/foundation/components/Camera/CameraComponent.ts
src/foundation/components/Light/LightComponent.ts
src/foundation/components/Mesh/MeshComponent.ts
src/foundation/components/MeshRenderer/MeshRendererComponent.ts
src/foundation/components/Physics/PhysicsComponent.ts
src/foundation/components/SceneGraph/SceneGraphComponent.ts
src/foundation/components/Skeletal/SkeletalComponent.ts
src/foundation/components/Transform/TransformComponent.ts
src/foundation/core/Component.ts
src/foundation/core/Config.ts
src/foundation/core/Entity.ts
src/foundation/exporter/Gltf2Exporter.ts
src/foundation/geometry/Primitive.ts
src/foundation/gizmos/Gizmo.ts
src/foundation/gizmos/ScaleGizmo.ts
src/foundation/gizmos/TranslationGizmo.ts
src/foundation/math/ColorRgba.ts
src/foundation/system/InputManager.ts
src/foundation/system/System.ts
src/sparkgear/SparkGearComponent.ts
src/webgl/WebGLStrategyUniform.ts

Add the TranslateGizmo and ScaleGizmo

feat: TranslationGizmo and ScaleGizmo

---

tsconfig.json

chore: add     "noUncheckedIndexedAccess": false,

---

samples/test_e2e/FXAA/main.ts
src/foundation/materials/core/Material.ts
src/foundation/renderer/Frame.test.ts
src/foundation/renderer/Frame.ts
src/foundation/renderer/RenderPass.ts
src/foundation/system/System.ts
src/index.ts

feat: renderpass

---

package.json
src/foundation/materials/contents/PbrShadingMaterialContent.ts

chore: default normal texture in pbr shader

---

src/foundation/memory/Buffer.ts

polly eye morph works correctly now

fix: Buffer padding

---

src/foundation/components/MeshRenderer/MeshRendererComponent.ts

fix: frustum culling

---

src/webgpu/WebGpuResourceRepository.ts

- Introduced a new bind group layout for mipmap generation, improving resource management.
- Updated the render pipeline to utilize the new bind group layout, ensuring proper binding of textures and samplers.
- Enhanced mipmap generation logic to streamline GPU resource usage and improve performance during texture operations.

feat: enhance mipmap generation in WebGpuResourceRepository

---

dist/esmdev/index.d.ts
src/foundation/enhanced_js_objects/Array.ts
src/foundation/helpers/MaterialHelper.ts
src/foundation/math/MathUtil.ts
src/foundation/misc/MiscUtil.ts

See https://github.com/mehmetoguzderin/RhodoniteTS/pull/2

fix: Add explicit return types to functions in public methods
